-- Create the 'TRANSFORM'ACCOUNT role
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the 'ETL' user and assign to role
CREATE USER IF NOT EXISTS ETL
  PASSWORD='etlPassword123'
  LOGIN_NAME='ETL'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE='TRANSFORM'
  DEFAULT_NAMESPACE='MOTOR_INSURANCE.BRONZE'
  COMMENT='ETL user for data transformation';

GRANT ROLE TRANSFORM to USER ETL;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS MOTOR_INSURANCE;

CREATE SCHEMA IF NOT EXISTS MOTOR_INSURANCE.BRONZE;
CREATE SCHEMA IF NOT EXISTS MOTOR_INSURANCE.SILVER;
CREATE SCHEMA IF NOT EXISTS MOTOR_INSURANCE.GOLD;

-- Set up permissions to role 'TRANSFORM'
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM; 
GRANT ALL ON DATABASE MOTOR_INSURANCE to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOTOR_INSURANCE to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOTOR_INSURANCE to ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MOTOR_INSURANCE.BRONZE to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOTOR_INSURANCE.BRONZE to ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MOTOR_INSURANCE.SILVER to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOTOR_INSURANCE.SILVER to ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MOTOR_INSURANCE.GOLD to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOTOR_INSURANCE.GOLD to ROLE TRANSFORM;

GRANT ALL ON ALL PROCEDURES IN SCHEMA MOTOR_INSURANCE.BRONZE to ROLE TRANSFORM;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MOTOR_INSURANCE.BRONZE to ROLE TRANSFORM;

GRANT ALL ON ALL PROCEDURES IN SCHEMA MOTOR_INSURANCE.SILVER to ROLE TRANSFORM;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MOTOR_INSURANCE.SILVER to ROLE TRANSFORM;

GRANT ALL ON ALL PROCEDURES IN SCHEMA MOTOR_INSURANCE.GOLD to ROLE TRANSFORM;
GRANT ALL ON FUTURE PROCEDURES IN SCHEMA MOTOR_INSURANCE.GOLD to ROLE TRANSFORM;
