SELECT TO_VARCHAR(LOG_DATE_TIME,'YYYYMMDDHH24MISS') C_DATE, T_DATE
FROM (
SELECT TRY_TO_TIMESTAMP(SUBSTR(A.LOG_DATE,1,11) || SUBSTR(A.LOG_TIME,1,8),'YYYY-MM-DD HH24:MI:SS') AS LOG_DATE_TIME, A.LOG_DATE, A.LOG_TIME
,SUBSTR(A.LOG_DATE,1,11) || SUBSTR(A.LOG_TIME,1,8) AS T_DATE
FROM MOTOR_INSURANCE.BRONZE.TWITTER A
);

SELECT DQ_SCORE, COUNT(1) AS CNT FROM MOTOR_INSURANCE.SILVER.TWITTER GROUP BY DQ_SCORE;

SELECT 2022 YEAR, 1 YEAR_PART, A.DQ_SCORE, A.SENTIMENT, C.BUSINESS_NAME, COUNT(1) SENTIMENT_COUNT
FROM MOTOR_INSURANCE.SILVER.TWITTER A,
MOTOR_INSURANCE.BRONZE.FIRMS_OF_INTEREST B,
MOTOR_INSURANCE.SILVER.FIRM_DETAILS C
WHERE A.MENTION_URL = B.MENTION_URL
AND B.TWITTER_HANDLE = C.TWITTER_HANDLE
GROUP BY A.DQ_SCORE, A.SENTIMENT, C.BUSINESS_NAME;

INSERT INTO MOTOR_INSURANCE.SILVER.TWITTER 
(LOG_DATE_TIME, MEDIA_TYPE, MENTION_URL, MENTION_CONTENT, SENTIMENT, COUNTRY, DQ_SCORE)
SELECT TRY_TO_TIMESTAMP(SUBSTR(A.LOG_DATE,1,11) || SUBSTR(A.LOG_TIME,1,8),'YYYY-MM-DD HH24:MI:SS') 
AS LOG_DATE_TIME,
MEDIA_TYPE, MENTION_URL, MENTION_CONTENT, SENTIMENT, COUNTRY,
CASE WHEN SENTIMENT NOT IN ('negative','positive','neutral') THEN 2
    WHEN LOG_DATE_TIME IS NULL OR COUNTRY = 'Not available' THEN 1
    ELSE 0
END DQ_SCORE
FROM MOTOR_INSURANCE.BRONZE.TWITTER A;


SELECT TRY_TO_DATE('2022-03-21 15:49:00','YYYY-MM-DD HH24:MI:SS') AS LOG_DATE_TIME;

select * from MOTOR_INSURANCE.BRONZE.TWITTER;
select * from MOTOR_INSURANCE.BRONZE.FORUMS;
select * from MOTOR_INSURANCE.BRONZE.TRUST_PILOT;
select * from MOTOR_INSURANCE.BRONZE.NEW_CASES;
select * from MOTOR_INSURANCE.BRONZE.RESOLVED_CASES;
select * from MOTOR_INSURANCE.BRONZE.EARLY_RESOLUTION;
select * from MOTOR_INSURANCE.BRONZE.FIRMS_OF_INTEREST;
select * from MOTOR_INSURANCE.BRONZE.FIRM_DETAILS;

select * from MOTOR_INSURANCE.SILVER.FIRMS_OF_INTEREST;
select * from MOTOR_INSURANCE.SILVER.FIRM_DETAILS;
select * from MOTOR_INSURANCE.SILVER.TWITTER;
select * from MOTOR_INSURANCE.SILVER.NEW_CASES;
select * from MOTOR_INSURANCE.SILVER.RESOLVED_CASES;

select * from MOTOR_INSURANCE.GOLD.TWITTER;
select * from MOTOR_INSURANCE.GOLD.NEW_CASES;
select * from MOTOR_INSURANCE.GOLD.RESOLVED_CASES;

call MOTOR_INSURANCE.SILVER.LOAD_FIRM_DETAILS();

SELECT A.DQ_SCORE, A.SENTIMENT, C.BUSINESS_NAME, COUNT(1) SENTIMENT_COUNT
FROM MOTOR_INSURANCE.SILVER.TWITTER A,
MOTOR_INSURANCE.BRONZE.FIRMS_OF_INTEREST B,
MOTOR_INSURANCE.SILVER.FIRM_DETAILS C
WHERE A.MENTION_URL = B.MENTION_URL
AND B.TWITTER_HANDLE = C.TWITTER_HANDLE
GROUP BY A.DQ_SCORE, A.SENTIMENT, C.BUSINESS_NAME;

drop PROCEDURE MOTOR_INSURANCE.SILVER.LOAD_TWITTER_DATA();
drop  PROCEDURE MOTOR_INSURANCE.SILVER.LOAD_FIRM_DETAILS();

SELECT BUSINESS_NAME, BUSINESS_GROUP, TOTAL_CASES, BANKING_CREDIT,
MORTGAGES_HOME_FINANCE, GENERAL_INSURANCE_PP, PPI, INVESTMENTS,
LIFE_PENSIONS
FROM MOTOR_INSURANCE.BRONZE.NEW_CASES
WHERE BUSINESS_GROUP <> 'TOTALS';	

select mention_url from MOTOR_INSURANCE.BRONZE.TWITTER;

CALL MOTOR_INSURANCE.BRONZE.LOAD_FIRMS_OF_INTEREST();

MOTOR_INSURANCE.BRONZE."LOAD_FIRMS_OF_INTEREST(NUMBER)"
SELECT B.*, TRIM(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) AS F_NAME
FROM MOTOR_INSURANCE.BRONZE.FIRM_DETAILS B;

SELECT A.*, B.*
FROM MOTOR_INSURANCE.BRONZE.RESOLVED_CASES A,  
(
SELECT DISTINCT CASE WHEN LENGTH(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) = 0 THEN B.BUSINESS_NAME ELSE TRIM(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) END AS BUSINESS_NAME,
FIRM_NAME, REFERENCE_NUMBER, BUSINESS_TYPE, STATUS
FROM MOTOR_INSURANCE.BRONZE.FIRM_DETAILS B
WHERE B.BUSINESS_TYPE = 'Firm'
) B
WHERE A.BUSINESS_NAME = B.BUSINESS_NAME;





SELECT A.*, B.*
FROM MOTOR_INSURANCE.BRONZE.RESOLVED_CASES A,  
(
SELECT DISTINCT CASE WHEN LENGTH(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) = 0 THEN B.BUSINESS_NAME ELSE TRIM(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) END AS BUSINESS_NAME,
FIRM_NAME, REFERENCE_NUMBER, BUSINESS_TYPE, STATUS
FROM MOTOR_INSURANCE.BRONZE.FIRM_DETAILS B
WHERE B.BUSINESS_TYPE = 'Firm'
) B
WHERE A.BUSINESS_NAME = B.BUSINESS_NAME;

CALL MOTOR_INSURANCE.BRONZE.LOAD_FIRMS_OF_INTEREST();

SELECT B.*, TRIM(SUBSTR(B.BUSINESS_NAME, 1, CHARINDEX('(',B.BUSINESS_NAME) - 1)) AS F_NAME
FROM MOTOR_INSURANCE.BRONZE.FIRM_DETAILS B
WHERE B.REFERENCE_NUMBER = '311492';
DROP PROCEDURE MOTOR_INSURANCE.BRONZE.LOAD_FIRMS_OF_INTEREST();

TRUNCATE TABLE MOTOR_INSURANCE.BRONZE.FIRMS_OF_INTEREST;

SELECT TRIM('@NorthwindTech:,#', '@:,#');

SELECT TRIM(CName,'*@:,;') FIRM_NAME FROM (
SELECT DISTINCT C.value::string AS CName
FROM MOTOR_INSURANCE.BRONZE.TWITTER,
LATERAL FLATTEN(input=>split(MENTION_CONTENT, ' ')) C
WHERE SUBSTR(CName,1,1) = '@'
);


