
CREATE OR REPLACE TABLE MOTOR_INSURANCE.GOLD.TWITTER (
YEAR INTEGER,
YEAR_PART INTEGER,
DQ_SCORE INTEGER,
SENTIMENT VARCHAR,
BUSINESS_NAME VARCHAR,
SENTIMENT_COUNT INTEGER
);

CREATE OR REPLACE TABLE MOTOR_INSURANCE.GOLD.NEW_CASES (
YEAR INTEGER,
YEAR_PART INTEGER,
BUSINESS_NAME VARCHAR,
BUSINESS_GROUP VARCHAR,
TOTAL_CASES VARCHAR,
BANKING_CREDIT VARCHAR,
MORTGAGES_HOME_FINANCE VARCHAR,
GENERAL_INSURANCE_PP VARCHAR,
PPI VARCHAR,
INVESTMENTS VARCHAR,
LIFE_PENSIONS VARCHAR
);		

CREATE OR REPLACE TABLE MOTOR_INSURANCE.GOLD.RESOLVED_CASES (
YEAR INTEGER,
YEAR_PART INTEGER,
BUSINESS_NAME VARCHAR,
BUSINESS_GROUP VARCHAR,
PERCENT_UPHELD VARCHAR,
RESOLVED_CASES VARCHAR,
PERCENT_BANKING_CREDIT VARCHAR,
PERCENT_MORTGAGES_HOME_FINANCE VARCHAR,
PERCENT_GENERAL_INSURANCE_PP VARCHAR,
PERCENT_PPI VARCHAR,
PPI_TOTAL VARCHAR,
PERCENT_INVESTMENTS VARCHAR,
PERCENT_LIFE_PENSIONS VARCHAR
);






