CREATE OR REPLACE TABLE MOTOR_INSURANCE.SILVER.TWITTER (
LOG_DATE_TIME TIMESTAMP_LTZ,
MEDIA_TYPE VARCHAR,
MENTION_URL VARCHAR,
MENTION_CONTENT VARCHAR,
SENTIMENT VARCHAR,
COUNTRY VARCHAR,
DQ_SCORE INTEGER
);

CREATE OR REPLACE TABLE MOTOR_INSURANCE.SILVER.FIRM_DETAILS (
REFERENCE_NUMBER VARCHAR,
BUSINESS_NAME VARCHAR,
TWITTER_HANDLE VARCHAR,
BUSINESS_TYPE VARCHAR,
STATUS VARCHAR
);

CREATE OR REPLACE TABLE MOTOR_INSURANCE.SILVER.NEW_CASES (
BUSINESS_NAME VARCHAR,
BUSINESS_GROUP VARCHAR,
TOTAL_CASES VARCHAR,
BANKING_CREDIT VARCHAR,
MORTGAGES_HOME_FINANCE VARCHAR,
GENERAL_INSURANCE_PP VARCHAR,
PPI VARCHAR,
INVESTMENTS VARCHAR,
LIFE_PENSIONS VARCHAR
);		

CREATE OR REPLACE TABLE MOTOR_INSURANCE.SILVER.RESOLVED_CASES (
BUSINESS_NAME VARCHAR,
BUSINESS_GROUP VARCHAR,
PERCENT_UPHELD VARCHAR,
RESOLVED_CASES VARCHAR,
PERCENT_BANKING_CREDIT VARCHAR,
PERCENT_MORTGAGES_HOME_FINANCE VARCHAR,
PERCENT_GENERAL_INSURANCE_PP VARCHAR,
PERCENT_PPI VARCHAR,
PPI_TOTAL VARCHAR,
PERCENT_INVESTMENTS VARCHAR,
PERCENT_LIFE_PENSIONS VARCHAR
);